#
# Configuration for Allen & Heath QU 24
#
Input:
    Name: 'MIDIMATE II Port 1'
    Channel: 1
Output:
    Name: 'qu'
    Ip: '192.168.0.150'
    Port: 51325
Mappings:
    - Name: 'MuteGroup'
      Target: 2
      CC: 0
      ValueOn: 127
    - Name: 'MuteGroup'
      Target: 3
      CC: 1
      ValueOn: 127
    - Name: 'TapDelay'
      Target: 2
      CC: 2
      ValueOn: 127
